name: Lint Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [20]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List files after checkout
        run: ls -laR

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install project deps
        run: pnpm install --frozen-lockfile --loglevel verbose

      - name: Run Biome lint
        run: pnpm biome check . > biome-output.log 2>&1
      
      - name: Upload report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: biome-lint-report-${{ github.sha}}
          path: biome-output.log
          retention-days: 5
