name: Lint Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Run Biome linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Biome
      run: npm install --save-dev --save-exact @biomejs/biome
      
    - name: Run Biome check
      run: npx biome check .
      
    - name: Upload diagnostics report (if errors)
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: biome-lint-report
        path: |
          biome.json
          biome-output.log