name: Lint Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10          # or omit to use package.json's "packageManager" setting :contentReference[oaicite:2]{index=2}

      - name: Install project deps
        run: pnpm install --frozen-lockfile

      - name: Run Biome lint
        run: pnpm exec biome check .
      
      - name: Upload report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: biome-lint-report
          path: biome-output.log
